<script>
jQuery(document).ready(function(e){
   alert(<?php echo $this->userid ?>);    
});    
</script>
<div class="spcallmain"></div>
    <div class="panel panel-default panel-block">
      <div class="list-group">
        <div class="list-group-item" id="responsive-bordered-table">
          <div class="form-group">
            <div class="row">
              <div class="col-xs-18 col-md-4">
                <h4 class="section-title hline">List of Users</h4>
              </div>
              <div class="col-xs-18 col-md-8">
                  <a class="btn btn-primary rgtbn" href="<?php echo $this->url('useradd') ?>">
                    <i class="icon-plus"></i> Add User
                    </a>
              </div>              
              <div class="linecvr"></div>
              <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
            </div>
          </div>

          <!--Basic Table-->
          <div class="tripdtalscrol">
              <div class="alert alert-success" style="display:none"></div>
            <div class="table-responsive">
              <table id="datatableuser" class="table table-bordered table-striped">
                <thead class="">
                  <tr>
                    <th>Order Id</th>
                    <th>Event Name</th>
                    <th>Event Date</th>
                    <th>Venue</th>
                    <th>Booked Seats</th>
                  </tr>
                </thead>
               
              </table>
            </div>
          </div>
          <div id="dialog-confirm" title="Confirm Deletion" style="display:none;">
            <p>
              <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
              Are you sure you want to delete this user?
            </p>
          </div>
          <div id="dialog-confirm-change" title="Confirm Status Change" style="display:none;">
            <p>
              <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
              Are you sure you want to change the status of this user?
            </p>
          </div>
        </div>
      </div>
    </div>

<?php $this->inlineScript()
           ->prependFile($this->basePath() . '/assets/admin/scripts/orderslisting.js', 'text/javascript')
           ->prependFile($this->basePath() . '/assets/datatables/media/js/dataTables.bootstrap.js', 'text/javascript')
           ->prependFile($this->basePath() . '/assets/datatables/media/js/jquery.dataTables.js', 'text/javascript');
            // ->prependFile($this->basePath() . '/js/bootstrap_paging.js')
            // ->prependFile($this->basePath() . '/js/placeholder/jquery.placeholder.js')?>
<?php
     $this->headLink()         
          ->appendStylesheet($this->basePath() . '/assets/datatables/media/css/dataTables.bootstrap.css')
          ->appendStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables.css');
?>
<script type="text/javascript">
function deleteUser(userid){
    $( "#dialog-confirm" ).dialog({
        resizable: false,
        height:180,
        modal: true,
        buttons: {
            "Yes": function() {
                    $( this ).dialog( "close" );
                    var URL = FULL_URL_PATH + '/admin/user/delete/'+ userid;
                    $.ajax({
                        method: "GET",
                        url: URL
                      })
                        .done(function( result ) {                                        
                            if(result == 1){
                                var target_row = $('#del_'+userid).closest("tr").get(0);                                
                                $(target_row).hide();                                
                                var oTable = $('#datatableuser').dataTable(); // JQuery dataTable function to delete the row from the table
                                oTable.fnDeleteRow(oTable.fnGetPosition(target_row));
                                $('.alert-success').html("User has been deleted successfully");
                                $('.alert-success').show();                                            
                            }                                      
                       });			
            },
            "No": function() {                                

                    $( this ).dialog( "close" );
            }
        }
    });
}

function activeInactiveUser(userId,changeType){
    $( "#dialog-confirm-change" ).dialog({
        resizable: false,
        height:180,
        modal: true,
        buttons: {
            "Yes": function() {
                    $( this ).dialog( "close" );
                    var URL = FULL_URL_PATH + '/admin/user/changestatus/'+ changeType+ '/'+userId ;
                    $.ajax({
                        method: "GET",
                        url: URL
                      })
                        .done(function( result ) {                                        
                            if(result == 1){
                                //var target_row = $('#del_'+userid).closest("tr").get(0);                                
                                //$(target_row).hide();                                
                                var oTable = $('#datatableuser').dataTable(); // JQuery dataTable function to delete the row from the table
                                oTable._fnAjaxUpdate();
                                $('.alert-success').html("User status has been updated successfully");
                                $('.alert-success').show();                                            
                            }                                      
                       });			
            },
            "No": function() {                                

                    $( this ).dialog( "close" );
            }
        }
    });
   }

</script>