<?php

namespace DoctrineORMModule\Proxy\__CG__\Admin\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \Admin\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventName', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'perfCode', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventDesc', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventAddress', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventZip', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventVenueTitle', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventVenueIcon', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageBig', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageMedium', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageSmall', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageBanner', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventArtist', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventLink', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'longitude', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'latitude', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'featured', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'status', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'createdDate', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'modifiedDate', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'category', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventCity', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventCountry', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'layout', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventSchedule', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventSeat', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventOption');
        }

        return array('__isInitialized__', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'id', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventName', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'perfCode', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventDesc', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventAddress', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventZip', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventVenueTitle', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventVenueIcon', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageBig', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageMedium', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageSmall', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventImageBanner', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventArtist', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventLink', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'longitude', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'latitude', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'featured', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'status', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'createdDate', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'modifiedDate', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'category', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventCity', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventCountry', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'layout', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventSchedule', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventSeat', '' . "\0" . 'Admin\\Entity\\Event' . "\0" . 'eventOption');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Event $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventName($eventName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventName', array($eventName));

        return parent::setEventName($eventName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfCode', array());

        return parent::getPerfCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerfCode($perfCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerfCode', array($perfCode));

        return parent::setPerfCode($perfCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventName', array());

        return parent::getEventName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventDesc($eventDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventDesc', array($eventDesc));

        return parent::setEventDesc($eventDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventDesc', array());

        return parent::getEventDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventAddress($eventAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventAddress', array($eventAddress));

        return parent::setEventAddress($eventAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventAddress', array());

        return parent::getEventAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventZip($eventZip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventZip', array($eventZip));

        return parent::setEventZip($eventZip);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventZip', array());

        return parent::getEventZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventVenueTitle($eventVenueTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventVenueTitle', array($eventVenueTitle));

        return parent::setEventVenueTitle($eventVenueTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventVenueTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventVenueTitle', array());

        return parent::getEventVenueTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventVenueIcon($eventVenueIcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventVenueIcon', array($eventVenueIcon));

        return parent::setEventVenueIcon($eventVenueIcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventVenueIcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventVenueIcon', array());

        return parent::getEventVenueIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventImageBig($eventImageBig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventImageBig', array($eventImageBig));

        return parent::setEventImageBig($eventImageBig);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventImageBig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventImageBig', array());

        return parent::getEventImageBig();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventImageMedium($eventImageMedium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventImageMedium', array($eventImageMedium));

        return parent::setEventImageMedium($eventImageMedium);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventImageMedium()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventImageMedium', array());

        return parent::getEventImageMedium();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventImageSmall($eventImageSmall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventImageSmall', array($eventImageSmall));

        return parent::setEventImageSmall($eventImageSmall);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventImageSmall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventImageSmall', array());

        return parent::getEventImageSmall();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventImageBanner($eventImageBanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventImageBanner', array($eventImageBanner));

        return parent::setEventImageBanner($eventImageBanner);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventImageBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventImageBanner', array());

        return parent::getEventImageBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventArtist($eventArtist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventArtist', array($eventArtist));

        return parent::setEventArtist($eventArtist);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventArtist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventArtist', array());

        return parent::getEventArtist();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventLink($eventLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventLink', array($eventLink));

        return parent::setEventLink($eventLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventLink', array());

        return parent::getEventLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', array($latitude));

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', array());

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatured($featured)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatured', array($featured));

        return parent::setFeatured($featured);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatured', array());

        return parent::getFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedDate($modifiedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedDate', array($modifiedDate));

        return parent::setModifiedDate($modifiedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedDate', array());

        return parent::getModifiedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Admin\Entity\Categories $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventCity(\Admin\Entity\City $eventCity = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventCity', array($eventCity));

        return parent::setEventCity($eventCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventCity', array());

        return parent::getEventCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventCountry(\Admin\Entity\Countries $eventCountry = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventCountry', array($eventCountry));

        return parent::setEventCountry($eventCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventCountry', array());

        return parent::getEventCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setLayout(\Admin\Entity\Layout $layout = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLayout', array($layout));

        return parent::setLayout($layout);
    }

    /**
     * {@inheritDoc}
     */
    public function getLayout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLayout', array());

        return parent::getLayout();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventSchedule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventSchedule', array());

        return parent::getEventSchedule();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventOption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventOption', array());

        return parent::getEventOption();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventSeat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventSeat', array());

        return parent::getEventSeat();
    }

}
