<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7 lt-ie10"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8 lt-ie10"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9 lt-ie10"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <title>Tapetickets - Login</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
		
		<?php echo $this->headLink(/*array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')*/)
                        ->prependStylesheet($this->basePath('assets/admin/styles/bootstrap.css'))
                        ->prependStylesheet($this->basePath('assets/admin/styles/proton.css'))
                        ->prependStylesheet($this->basePath('assets/admin/styles/vendor/animate.css')) 
                        ->prependStylesheet($this->basePath('assets/admin/styles/font-awesome.css'))
                        ->prependStylesheet($this->basePath('assets/admin/styles/font-titillium.css'))
						
						?>
		   <!-- Scripts -->
		 <!-- Common Scripts: -->
        <script>
        (function () {
          var js;
          if (typeof JSON !== 'undefined' && 'querySelector' in document && 'addEventListener' in window) {
            js = '//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js';
          } else {
            js = '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js';
          }
          document.write('<script src="' + js + '"><\/script>');
        }());
        </script>  
        <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/additional-methods.min.js"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath('assets/admin/scripts/vendor/modernizr.js'))
            ->prependFile($this->basePath('assets/admin/scripts/vendor/jquery.cookie.js'))
            ->prependFile($this->basePath('js/additional-methods.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
     
    </head>
		<?php echo $this->content; ?>
</html>
