<div class="row">
    <div class="col-md-12 pad12">							
        <div class="panel panel-default panel-block">
            <div class="list-group">
                <div class="list-group-item" id="masked-input-fields">
                    <h4 class="section-title">Edit Email Template</h4>
                    <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
                    <?php if(!empty($success)) {  ?>
                        <div class="alert alert-success fade in"><?php echo $success; ?></div>
                    <?php } ?>
                    <?php if(!empty($error)) { ?>
                        <div class="alert alert-danger fade in"><?php echo $error; ?></div>
                    <?php } ?>
                        
                    <?php
                        $form->setAttribute('action', $this->url('editemail',array('emailid'=>$emailid)));
                        $form->setAttribute('class', "form-horizontal");
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
                            <label class="col-lg-4 control-label" for="emailsub">
                               Email Subject
                            </label>
                            <div class="col-lg-8">								
                                    <?php echo $this->formRow($form->get('emailsub')); ?>
                            </div>
                    </div>
                    <div class="form-group">
                            <label class="col-lg-4 control-label" for="emalcontent">
                               Email Content
                            </label>
                            <div class="col-lg-8">								
                                    <?php echo $this->formRow($form->get('emailcontent')); ?>
                            </div>
                    </div>           
                               

                    <div class="btnaddriv form-group">
                        <div class="row show-grid">
                            <div class="col-xs-6"><?php echo $this->formRow($form->get('submitbutton')); ?></div>
                            <div class="col-xs-6"><button class="btn btn-default saveaddriv unpaistridt" type="button" onclick="window.location ='<?php echo $this->url('emailindex') ?>';">Cancel</button></div>
                        </div>                     
                    </div>
					
                    <?php echo $this->form()->closeTag(); ?>
					
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.validate.js'); ?>
<script>
$( document ).ready(function() {    
    var validator = $("#editemail").submit(function() {			
			tinyMCE.triggerSave();
		}).validate({
                        errorClass:'validation-error',
			ignore: "",
			rules: {				
				'emailsub':{ 
                                    required: true,
                                    htmltags: true,
                                    maxlength: 60
                                },
                                'emailcontent':{ required: true }                                
                                    
			},
                         messages : {
                            'emailsub' : {
                                    required: "Please enter Email Subject",
                                    htmltags: "HTML Tags are not allowed",
                                    maxlength: "Email Subject cannot exceed 60 characters"
                            },	
                            'emailcontent' : {
                                    required: "Please enter Email Content"
                            }                         
            
                         },			
                        }); 
                        /**
                        * This function check html tags in field value
                        * @Author Vinod Kandwal
                        */
                        jQuery.validator.addMethod("htmltags", function checkHTMLTags(value, element, params) { 
                                if(value.match(/([\<])([^\>]{1,})*([\>])/i)==null){
                                        return true;
                                }else{
                                        return false;
                                }
                        });
                        validator.focusInvalid = function() {
			// put focus on tinymce on submit validation
                            if( this.settings.focusInvalid ) {
                                try {
                                        var toFocus = $(this.findLastActive() || this.errorList.length && this.errorList[0].element || []);
                                        if (toFocus.is("textarea")) {
                                                tinyMCE.get(toFocus.attr("id")).focus();
                                        } else {
                                                toFocus.filter(":visible").focus();
                                        }
                                } catch(e) {
                                        // ignore IE throwing errors when focusing hidden elements
                                }
                            }
                        }     
 });
          
  
</script>
<script>  
    tinyMCE.init({
    selector:'textarea',
    theme : "modern",  
    mode : "exact",  
    elements : "template",  
    width : "580",  
    height: "200",  
    plugins : "paste, table, code",  
    theme_modern_resizing : true,  
    theme_modern_resizing_use_cookie : false,  
    theme_modern_toolbar_location : "top",  
    theme_modern_buttons1 : "formatselect, bold, italic, underline, strikethrough, |, justifyleft, justifycenter, justifyright, justifyfull, |, bullist, numlist, |, outdent, indent, blockquote, |, undo, redo, cleanup, removeformat, pasteword, code ",  
    theme_modern_buttons2 : "link, unlink, anchor, |, image, hr , sub, sup, charmap, |, forecolor, backcolor, |, tablecontrols",  
    theme_modern_buttons3 : "",  
    theme_modern_blockformats : "p,h1,h2,h3,blockquote,dt,dd",
    onchange_callback: function(editor) {tinyMCE.triggerSave();
            $("#" + editor.id).valid();
        }
    });  
</script>  
