<div class="spcallmain"></div>
<div class="panel panel-default panel-block">
    <div class="list-group">
        <div id="responsive-bordered-table" class="list-group-item">
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-18 col-md-4">
                      <h4 class="section-title hline">Email Template Listing</h4>
                    </div>                    
                    <div class="alert alert-success fade in" style="display:none;"></div> 
                    <div id="error" style="display:none;"></div>
                    <div class="linecvr"></div>  
                    <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
                    <table id="datatablesemail" class="table table-striped table-bordered responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>                                 
                                <th class="min-tablet">Email Subject</th>
                                <th class="min-tablet">Status</th>
                                <th class="min-tablet">Action</th>
                            </tr>
                        </thead>				
                    </table>								 
                    <div class="row-fluid">
                          <div class="span6"></div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>   
<?php $this->inlineScript()
           ->prependFile($this->basePath() . '/assets/admin/scripts/emaillisting.js', 'text/javascript')
           ->prependFile($this->basePath() . '/assets/datatables/media/js/dataTables.bootstrap.js', 'text/javascript')
           ->prependFile($this->basePath() . '/assets/datatables/media/js/jquery.dataTables.js', 'text/javascript');            

     $this->headLink()         
          ->appendStylesheet($this->basePath() . '/assets/datatables/media/css/dataTables.bootstrap.css')
          ->appendStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables.css');
     ?>
<script>
$( document ).ready(function() {
    $( "#dialog-confirm" ).hide();
});
</script>