<div class="container main mtop-55">
    <link href='//fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>

    <link href="<?php echo $this->basePath('/assets/frontend/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->basePath('/assets/frontend/css/theme-style.css'); ?>" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->basePath('/assets/frontend/css/custom-style.css'); ?>" rel="stylesheet" type="text/css">
    <!--added by Yesh-->
    <link href="<?php echo $this->basePath('/assets/frontend/css/intlTelInput.css'); ?>" rel="stylesheet" type="text/css">
    <script type="text/javascript">
        var FULL_URL_PATH = '<?php echo $this->url('home', array(), array('force_canonical' => true)); ?>';
    </script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>
     <script src="<?php echo $this->basePath('/assets/frontend/js/bootstrap3-typeahead.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('/assets/frontend/js/common.js'); ?>"></script>
    <script src="<?php echo $this->basePath('/js/jquery.validate.js'); ?>"></script>
    <script src="<?php echo $this->basePath('/assets/jquery-countdownTimer/jquery.countdownTimer.js'); ?>"></script>
    <!--added by Yesh-->
    <script src="<?php echo $this->basePath('/assets/frontend/js/intlTelInput.js'); ?>"></script>
    <?php
    $postedData = $checkoutContainer;
    ?>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            //get cookie current time
            function getCookie(name) {
                var nameEQ = name + "=";
                var cookieArray = document.cookie.split('; ');
                for (var i = 0; i < cookieArray.length; i++) {
                    var cookie = cookieArray[i];
                    if (cookie.indexOf(nameEQ) === 0) {
                        cookie = cookie.substring(nameEQ.length, cookie.length);
                        return cookie;
                    }
                }
            }
            //remove selected seats from database if times run out
            function removeSeatSelection(obj, eventID, scheduleID) {
                var c = false;
                var titleObj = JSON.stringify(obj);
                var path = '<?php echo $this->url('ajaxremoveselection'); ?>';
                jQuery.ajax({
                    type: 'POST',
                    url: path,
                    dataType: 'json',
                    async: false,
                    data: {'eventID': eventID, 'titleObj': titleObj, 'scheduleID': scheduleID},
                    success: function (response) {
                        if (response.status === 'success') {
                            c = true;
                        }
                    }
                });
                return c;
            }
            //start Timer
            function startTimer(duration, display) {
                var timer = duration, minutes, seconds;
                cycleTimer = setInterval(function () {
                    minutes = parseInt(timer / 60, 10);
                    seconds = parseInt(timer % 60, 10);
                    minutes = minutes < 10 ? "0" + minutes : minutes;
                    seconds = seconds < 10 ? "0" + seconds : seconds;
                    display.text(minutes + ":" + seconds);
                    var tmpTxt = jQuery('#time').text();
                    var globTimer = tmpTxt;
                    document.cookie = 'globTimer=' + globTimer + '; path=/';
                    if (--timer < 0) {
                        timer = duration;
                        clearInterval(cycleTimer);//once time is done
                        cycleTimer = '';
                        document.cookie = 'seatsArray=""; path=/';
                        document.cookie = 'globTimer=""; path=/';
                        var c = removeSeatSelection();
                        if (c) {
                            window.location = '<?php echo $this->url('checkouttimeout', array('eventId' => $postedData['id'])); ?>';
                        }
                    }
                }, 1000);
            }
            var globTimer = getCookie('globTimer');//get global timer
            var timeArray = globTimer.split(':');
            var seconds = ((timeArray[0]) * 60 + (+timeArray[1]));
            var minOneFive = seconds, display = jQuery('#time');//current minutes
            startTimer(minOneFive, display);
        });
    </script>
    <style type="text/css">
        li.zone {
            font-weight: bold;
        }
        span.seatLable {
            margin-left: 10px;
        }
    </style>
    <div class="row">
        <div class="col-md-8 col-lg-8 col-sm-8">
            <div class="checkout">
                <h2 class="heading"><span>Checkout</span></h2>
                <p class="order-time">Time left to complete your order is <span id="time"></span></p>
                <div class="row form-element">
                    <div class="col-md-8 col-sm-8">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('confirmorder'));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        ?>
                        <div class="method ticket-qty">
                            <div class="media">
                                <div class="media-left">Ticket quantity</div>
                                <div class="media-body">
                                    <?php echo $this->formRow($form->get('quantity')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="method">
                            <h5>Contact information</h5>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('email')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('phoneno')); ?>
                            </div>
                        </div>
                        <div class="method">
                            <h5>billing address</h5>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('firstname')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('lastname')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('streetaddress')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('country')); ?>
                            </div>
                            <div class="form-group">
                                <?php echo $this->formRow($form->get('city')); ?>
                            </div>
                            <div class="form-group checkbox-custom termscheck">
                                <div class="checkbox-box">
                                    <?php echo $this->formRow($form->get('box-chk')); ?>
                                    <label for="box-chk" class="for-checkbox">&nbsp;I agree to TapeTickets terms &amp; services </label>
                                </div>
                                </div>
                            <?php
                            if ($userId == 34) {
                                ?><a class="btn-blue pull-right" data-target="#login" data-toggle="modal" href="javascript:void(0)">Sign In & Proceed</a><?php
                                } else {
                                    ?><button class="btn-blue"  type="submit"  onClick="">Continue</button><?php
                            }
                            ?>
                        </div>
                        <!--/Billing Address-->
                        <?php echo $this->form()->closeTag(); ?>
                        <!--</form>-->
                    </div>
                </div>
            </div>
            <!--/ticket-preview--> 
        </div>
        <div class="col-md-4 col-lg-4 col-sm-4">
            <div class="sidebar">
                <div class="tickets-details">
                    <h3 class="heading-blue">ticket details</h3>
                    <h4 class="heading-18"><?php echo $postedData['eventName'] ?><span class="text-gray"><?php echo $postedData['eventVenueTitle'] ?></span></h4>
                    <span class="block bold">
                        <?php
                        $date = date('F d, Y', strtotime($postedData['eventDate']));
                        $time = date('h:i A', strtotime($postedData['eventTime']));
                        echo $date . "&nbsp;&nbsp;•&nbsp;&nbsp;" . $time;
                        //April 16, 2015  •  09:00 PM 
                        ?>
                    </span>
                </div>
                <!--/ticket details-->
                <h3 class="heading-blue">order summary</h3>
                <ul id="selectedSeats">
                    <?php
                    foreach ($selectedSeats as $row) {
                        ?><li class="zone"><?= ucwords($row->zoneTitle); ?></li><?php
                        $sC = count($row->seatIds);
                        $num = 0;
                        foreach ($row->seatIds as $Id) {
                            $num++;
                            ?><span class="seatLable"><?= explode("_", $Id)[1]; ?></span><?php
                                if ($num !== $sC) {
                                    ?>, <?php
                            }
                        }
                    }
                    ?>
                </ul>
                <div class="total-aed"><span class="text-gray">Total</span><?php echo $postedData['totalAmount']; ?> AED</div>
            </div>
            <!--/sidebar--> 
            <!--//added by Sathish - 13012016-->
            <div style="padding-top:20px;">
                <span><input id="backbtn" type="button" class="btn-blue pull-right" value="Change Seats" /></span>
            </div>
        </div>
    </div>
    <!--/row--> 
</div>
<!--/main-->
<script type="text/javascript">
    $(document).ready(function () {
        $("#phoneno").intlTelInput();
        //added by Sathish - 13012016
        $('#backbtn').click(function () {
            parent.history.back();
            return false;
        });
        $("#checkoutform").validate({
            errorClass: 'valerror',
            rules: {
                email: {required: true, email: true},
                phoneno: {required: true},
                saved_cards: {required: true},
                card_type: {required: true},
                cardno: {maxlength: 16, htmltags: true, required: true},
                securityno: {required: true, htmltags: true},
                month: {required: true, positiveNumber: true},
                year: {required: true, positiveNumber: true},
                firstname: {required: true, htmltags: true},
                lastname: {required: true, htmltags: true},
                streetaddress: {required: true, htmltags: true},
                city: {required: true},
                country: {required: true},
                'box-chk': {required: true}
            },
            messages: {
                email: {
                    required: "Please enter email",
                    email: "Please enter valid email address"
                },
                phoneno: {
                    required: "Please enter phone no",
                },
                card_type: {
                    required: "Please select card type"
                },
                saved_cards: {
                    required: "Please choose any saved card or new card for checkout."
                },
                cardno: {
                    maxlength: "Card Number cannot exceed 16 Characters",
                    htmltags: "HTML Tags not supported",
                    required: "Please enter card number"
                },
                securityno: {
                    htmltags: "HTML tags not supported",
                    required: "Please enter security code"
                },
                month: {
                    required: "Please select expiry month of card",
                    positiveNumber: "Please check card expiry month"
                },
                year: {
                    required: "Please select expiry year of card",
                    positiveNumber: " Please check card expiry year"
                },
                firstname: {
                    htmltags: "HTML tags not supported",
                    required: "Please enter first name"
                },
                lastname: {
                    htmltags: "HTML tags not supported",
                    required: "Please enter last name"
                },
                streetaddress: {
                    htmltags: "HTML tags not supported",
                    required: "Please enter street address"
                },
                city: {
                    required: "Please select city"
                },
                country: {
                    required: "Please select country"
                },
                'box-chk': {
                    required: "Please agree to our terms and services"
                },
            }/*,
             submitHandler: function(form) {
             var formData = $("#checkoutform").serialize();                                                   
             $.post('<?php echo $this->url('confirmorder'); ?>', formData, function(response){
             var obj = jQuery.parseJSON( response );
             var status = obj.status;
             var msg = obj.msg;                                  
             if(status == 1){
             
             }else if(status == -1){                               
             
             }else{
             
             }
             });
             }*/
        });
        $.validator.addMethod("htmltags", checkHTMLTags);
        $.validator.addMethod('positiveNumber', function (value) {
            return Number(value) > 0;
        }, 'Enter a positive number.');
        jQuery("#saved_cards").change(function (e) {
            var activecard = this.value;
            //$('#editcard #cardid').val(activecard);  
            if (activecard != "") {
                //var url = FULL_URL_PATH+"event/getusercarddet/"+activecard;   
                if (activecard == 0) {
                    disabledToggle(1);
                    makeFieldsBlank();
                    return;
                }
                var url = FULL_URL_PATH + "getcarddetails/" + activecard;
                $.post(url, function (response) {
                    var obj = jQuery.parseJSON(response);
                    var status = obj.status;
                    if (status == 1) {
                        //$("#editcard .title").val(obj.card.title);
                        disabledToggle(1);
                        $("#cardno").val(atob(obj.card.cardno));
                        $("#month").val(obj.card.month);
                        $("#year").val(obj.card.year);
                        $("input:radio[name=card_type][value=" + obj.card.cardtype + "]").attr('checked', 'checked');
                    } else if (status == -1) {
                        alert(msg);
                        //window.location = '<?php echo $this->url('home') ?>';
                    } else {
                        /* $(".cardform .alert-error").html(msg);
                         $(".cardform .alert-error").show();
                         $(".cardform .alert-success").hide(); */
                    }
                });
            } else {
                alert("Select any saved card");
                makeFieldsBlank();
                disabledToggle(0);
            }
        });
    });
    function makeFieldsBlank() {
        $("#cardno").val("");
        $("#month").val("");
        $("#year").val("");
    }
    function disabledToggle(toggleVal) {
        if (toggleVal) {
            $("#cardno").prop("disabled", false);
            $("#securityno").prop("disabled", false);
            $("#month").prop("disabled", false);
            $("#year").prop("disabled", false);
            $('input:radio[name=card_type]').prop("disabled", false);
        } else {
            $("#cardno").prop("disabled", true);
            $("#securityno").prop("disabled", true);
            $("#month").prop("disabled", true);
            $("#year").prop("disabled", true);
            $('input:radio[name=card_type]').prop("disabled", true);
        }
    }
    function getCity(countryid) {
        if (countryid != "") {
            var fetch_city_url = "<?php echo $this->url('getcities'); ?>" + countryid;
            $.ajax({
                url: fetch_city_url
            }).done(function (data) {
                $('#city').html(data);
            });
        } else {
            $('#city').val("");
        }
    }
</script>
