<div class="spcallmain"></div>
<div class="panel panel-default panel-block">
    <div class="list-group">
        <div class="list-group-item" id="responsive-bordered-table">
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-18 col-md-4">
                        <h4 class="section-title hline">Events</h4>
                    </div>
                    <div class="col-xs-18 col-md-6">
                    </div>
                    <div class="col-xs-18 col-md-2">
                        <a title="Add Event" href="<?php echo $this->url('addevent'); ?>" class="btn btn-primary"><i class="icon-plus"></i>&nbsp;Add Event</a>
                    </div>
                    <div class="linecvr"></div>
                    <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
                </div>
            </div>
            <!--Basic Table-->
            <div class="tripdtalscrol">
                <div class="alert alert-success" style="display:none"></div>
                <div class="table-responsive">
                    <table id="datatableevents" class="table table-bordered table-striped">
                        <thead class="">
                            <tr>
                                <th>Event Name</th>
                                <th>Artist</th>
                                <th>Venue</th>
                                <!--th>Date & Time</th>-->
                                <th>Category</th>
                                <!--<th>Ticket Available</th>-->
                                <th>Action</th>
                            </tr>
                        </thead>

                    </table>
                </div>
            </div>
            <div id="dialog-confirm" title="Confirm Deletion" style="display:none;">
                <p>
                    <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
                    Are you sure you want to delete this event?
                </p>
            </div>
            <div id="dialog-confirm-cancel" title="Confirm Cancel" style="display:none;">
                <p>
                    <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
                    We found that this event has future date and if any user has opted to attend the event then you need to refund the amount. 
                    Are you sure you want to cancel this event?
                </p>
            </div>
            <div id="dialog-confirm-change" title="Confirm Status Change" style="display:none;">
                <p>
                    <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
                    Are you sure you want to change the status of this event?
                </p>
            </div>
        </div>
    </div>
</div>

<?php
$this->inlineScript()->prependFile($this->basePath() . '/assets/admin/scripts/eventslisting.js', 'text/javascript')->prependFile($this->basePath() . '/assets/datatables/media/js/dataTables.bootstrap.js', 'text/javascript')->prependFile($this->basePath() . '/assets/datatables/media/js/jquery.dataTables.js', 'text/javascript');
?>
<?php
$this->headLink()->appendStylesheet($this->basePath() . '/assets/datatables/media/css/dataTables.bootstrap.css')->appendStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables.css');
?>
<script type="text/javascript">
    function deleteEvent(eventId) {
        $("#dialog-confirm").dialog({
            resizable: false,
            height: 180,
            modal: true,
            buttons: {
                "Yes": function () {
                    $(this).dialog("close");
                    var URL = FULL_URL_PATH + '/admin/event/delete/' + eventId;
                    $.ajax({
                        method: "GET",
                        url: URL
                    })
                            .done(function (result) {
                                if (result == 1) {
                                    var target_row = $('#del_' + eventId).closest("tr").get(0);
                                    $(target_row).hide();
                                    var oTable = $('#datatableevents').dataTable(); // JQuery dataTable function to delete the row from the table
                                    oTable.fnDeleteRow(oTable.fnGetPosition(target_row));
                                    $('.alert-success').html("Event has been deleted successfully");
                                    $('.alert-success').show();
                                }
                            });
                },
                "No": function () {

                    $(this).dialog("close");
                }
            }
        });
    }
    function cancelEvent(eventId) {
        $("#dialog-confirm-cancel").dialog({
            resizable: false,
            height: 280,
            modal: true,
            buttons: {
                "Yes": function () {
                    $(this).dialog("close");
                    var URL = FULL_URL_PATH + '/admin/event/cancel/' + eventId;
                    $.ajax({
                        method: "GET",
                        url: URL
                    })
                            .done(function (result) {
                                if (result == 1) {
                                    var target_row = $('#del_' + eventId).closest("tr").get(0);
                                    $(target_row).hide();
                                    var oTable = $('#datatableevents').dataTable(); // JQuery dataTable function to delete the row from the table
                                    oTable.fnDeleteRow(oTable.fnGetPosition(target_row));
                                    $('.alert-success').html("Event has been cancelled successfully");
                                    $('.alert-success').show();
                                }
                            });
                },
                "No": function () {

                    $(this).dialog("close");
                }
            }
        });
    }

    function activeInactiveEvent(eventId, changeType) {
        $("#dialog-confirm-change").dialog({
            resizable: false,
            height: 180,
            modal: true,
            buttons: {
                "Yes": function () {
                    $(this).dialog("close");
                    var URL = FULL_URL_PATH + '/admin/event/changestatus/' + changeType + '/' + eventId;
                    $.ajax({
                        method: "GET",
                        url: URL
                    })
                            .done(function (result) {
                                if (result == 1) {
                                    var oTable = $('#datatableevents').dataTable(); // JQuery dataTable function to delete the row from the table
                                    oTable._fnAjaxUpdate();
                                    $('.alert-success').html("Event status has been updated successfully");
                                    $('.alert-success').show();
                                }
                            });
                },
                "No": function () {

                    $(this).dialog("close");
                }
            }
        });
    }

    function editEvent(eventId) {
        return window.location.href = FULL_URL_PATH + '/admin/event/edit/' + eventId;
    }
    function layoutEvent(eventId) {
        return window.location.href = FULL_URL_PATH + '/admin/event/layout/' + eventId;
    }

</script>