<div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3">
        <h3>about tape tickets</h3>
        <ul>
          <li><a href="<?php echo $this->url('aboutus') ?>">About Us</a></li>
          <li><a href="<?php echo $this->url('terms') ?>">Terms &amp; Conditions</a></li>
          <li><a href="<?php echo $this->url('contactus') ?>">Contact Us</a></li>
          <li><a href="<?php echo $this->url('privacypolicy') ?>">Privacy Policy</a></li>
          <li><a href="<?php echo $this->url('deliverypolicy') ?>">Purchase Policy</a></li>
          <li class="dropdown"> 
           <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><?php if($this->active_city != ""){ echo $this->active_city; }else { ?>Dubai,UAE <?php } ?> <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
              <?php foreach($cities as $city): ?>
                <li><a href="<?php echo $this->url('eventsearch',array('type'=>'city','searchval'=>$city->getId())); ?>"><?php echo $city->getCityName(); ?></a></li>
              <?php endforeach; ?>
            </ul>
          </li>
          <!--<li><a href="#" class="text-yellow">List Your Event</a></li>-->
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <h3>we are here to help</h3>
        <ul>
          <li><a href="<?php echo $this->url('faq') ?>">FAQ</a></li>
          <li><a href="<?php echo $this->url('printingticket') ?>">Printing Tickets</a></li>
          <li><a href="<?php echo $this->url('support') ?>">Support</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <h3>connect with us</h3>
        <ul>
          <li><a href="#"><i class="fa fa-facebook"></i>Facebook</a></li>
          <li><a href="#"><i class="fa fa-twitter"></i>Twitter</a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i>Google +</a></li>
          <li><a href="#"><i class="fa fa-at"></i>Email</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <p> <a href="<?php echo $this->url('eventadd') ?>">Add Event</a></p>
        <p class="copyrights"><img src="<?php echo $this->basePath('/assets/frontend/images/img-logo.png');?>" alt=""><br>
          TapeTickets &copy; 2015<br>
          All rights reserved. </p>
      </div>
    </div>
  </div>
<style>

#multipledataset .league-name {
  margin: 0 20px 5px 20px;
  padding: 3px 0;
  border-bottom: 1px solid #ccc;
}
</style>