<div class="row">
	<div class="col-md-12 pad12">
							
		<div class="panel panel-default panel-block">
			<div class="list-group">
				<div class="list-group-item" id="masked-input-fields">
					<h4 class="section-title">Add Category</h4>
					<?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
					<?php if(!empty($success)) {  ?>
                                        <div class="alert alert-success fade in"><?php echo $success; ?></div>
                                        <?php } ?>
                                            <?php if(!empty($error)) { ?>
					<div class="alert alert-danger fade in"><?php echo $error; ?></div>
				<?php } ?>
					<?php
						$form->setAttribute('action', $this->url('addcategory'));
						$form->setAttribute('class', "form-horizontal");
						$form->prepare();                                                
						echo $this->form()->openTag($form);
					?>
						<div class="form-group">
							<label class="col-lg-4 control-label" for="categoryName">
							   Category Name
							</label>
							<div class="col-lg-8">								
								<?php echo $this->formRow($form->get('catname')); ?>
							</div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-lg-4 control-label" for="categoryName">
                                                       Category Icon
                                                    </label>
                                                    <div class="col-lg-8">								
                                                        <?php echo $this->formRow($form->get('fileupload')); ?>							
                                                    </div>
                                                </div>												
						<div class="btnaddriv">
                                                    <div class="row show-grid">
                                                        <div class="col-xs-6"><?php echo $this->formRow($form->get('submitbutton')); ?></div>
                                                    <div class="col-xs-6"><button class="btn btn-default saveaddriv unpaistridt" type="button" onclick="window.location ='<?php echo $this->url('categoryindex') ?>';">Cancel</button></div>
                                                    </div>                                             
						</div>                                                
					
					<?php echo $this->form()->closeTag(); ?>
					
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/jquery.validate.js'); ?>
<script>
$( document ).ready(function() {
	jQuery.validator.setDefaults({            
            success: "valid"
        });       
	$("#addcat").validate({
		errorClass:'validation-error',
		rules: {				
			catname:{ 
                            required: true,
                            htmltags: true,
                            maxlength: 60
                        },
                        fileupload:{
                            required: true,
                            extension: "jpg|jpeg|gif|png"
                        },
		},
        messages: {           
			'catname' : {
                                required: "Please enter Category Name",
                                htmltags: "html tags not allowed",
                                maxlength: "Category Name cannot be greater than 60 characters"
                        },	
                        'fileupload' : {
                                required: "Please Upload File",
                                extension: "Only jpg,gif,png extensions are supported."
                        },			
        },
		submitHandler: function(form) {
			form.submit();
		}
	});
        /**
        * This function check html tags in field value
        * @Author Vinod Kandwal
        */
        jQuery.validator.addMethod("htmltags", function checkHTMLTags(value, element, params) { 
                if(value.match(/([\<])([^\>]{1,})*([\>])/i)==null){
                        return true;
                }else{
                        return false;
                }
        });
});

</script>
