<div class="spcallmain"></div>
<div class="panel panel-default panel-block">
    <div class="list-group">
        <div id="responsive-bordered-table" class="list-group-item">
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-18 col-md-4">
                      <h4 class="section-title hline">Category Listing</h4>
                    </div>
                    <div class="col-xs-18 col-md-8">
                        <a class="btn btn-primary rgtbn" href="<?php echo $this->url('addcategory') ?>">
                             <i class="icon-plus"></i> Add Category
                        </a>
                    </div>                    
                    <div id="error" style="display:none;"></div>
                    <div class="linecvr"></div>
                    <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
                    <div class="alert alert-success fade in" style="display:none;"></div> 
                    <table id="datatablesuser" class="table table-striped table-bordered responsive" cellspacing="0" width="100%">
                        <thead>
                            <tr>                                             
                                <th class="min-tablet">Category Icon</th>
                                <th class="min-tablet">Category Name</th>
                                <th class="min-tablet">Actions</th>
                            </tr>
                        </thead>				
                    </table>								 
                    <div class="row-fluid">
                          <div class="span6"></div> 
                   </div>
                    <div id="dialog-confirm" title="Confirm Deletion">
                          <p>
                        <span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span>
                        Are You sure you want to delete this category?
                      </p>
                    </div>
                </div> 
	   <!--<button id="demo-bootbox-confirm" class="btn btn-info">Confirm</button>-->
	   </div>		
	 </div> 
    </div>
   <!--/dashboar-->
</div><!--/content-body -->
<?php $this->inlineScript()
           ->prependFile($this->basePath() . '/assets/admin/scripts/categorylisting.js', 'text/javascript')
           ->prependFile($this->basePath() . '/assets/datatables/media/js/dataTables.bootstrap.js', 'text/javascript')
           ->prependFile($this->basePath() . '/assets/datatables/media/js/jquery.dataTables.js', 'text/javascript');
            // ->prependFile($this->basePath() . '/js/bootstrap_paging.js')
            // ->prependFile($this->basePath() . '/js/placeholder/jquery.placeholder.js')?>
<?php
     $this->headLink()         
          ->appendStylesheet($this->basePath() . '/assets/datatables/media/css/dataTables.bootstrap.css')
          ->appendStylesheet($this->basePath() . '/assets/datatables/media/css/jquery.dataTables.css');
?>
<script>
$( document ).ready(function() {
    $( "#dialog-confirm" ).hide();
});
function delcategory(catid,catname) {  
        //alert(catname);
	$( "#dialog-confirm" ).dialog({
		resizable: false,
		height:180,
		modal: true,
		buttons: {
			"Yes": function() {
                                $( this ).dialog( "close" );
				var URL = FULL_URL_PATH + '/admin/category/categorydelete/'+ catid;
                                $.ajax({
                                    method: "POST",
                                    url: URL
                                  })
                                    .done(function( result ) {                                        
                                        if(result == 1){
                                            var target_row = $('#'+catid).closest("tr").get(0);                                                                            
                                            $(target_row).hide();                                
                                            var oTable = $('#datatablesuser').dataTable(); // JQuery dataTable function to delete the row from the table
                                            oTable.fnDeleteRow(oTable.fnGetPosition(target_row));
                                            $('.alert-success').html(catname+" has been Deleted");
                                            $('.alert-success').show();                                            
                                        }                                      
                                   });			
			},
			"No": function() {                        
                               
				$( this ).dialog( "close" );
			}
		}
	});
}    
</script>
			