<h5>change password</h5>
<?php
$form = $this->form;
$form->setAttribute('action', '');
$form->prepare();
echo $this->form()->openTag($form);
?>
    <div class="form-group">
      <?php echo $this->formRow($form->get('oldpassword')); ?>
    </div>
    <div class="form-group">
      <?php echo $this->formRow($form->get('newpassword')); ?>
    </div>
    <div class="form-group">
      <?php echo $this->formRow($form->get('confnewpass')); ?>
    </div>
    <?php echo $this->formRow($form->get('savebtn')); ?>
    <?php echo $this->form()->closeTag(); ?>
<script>
       $( document ).ready(function() {	
	$("#userchangepass").validate({
		errorClass:'validation-error',
		rules: {				
			oldpassword:{ required: true },
			newpassword:{ required: true, minlength: 6, maxlength: 16 },
			confnewpass: { required: true, equalTo: "#newpassword", minlength: 6, maxlength: 16 },
		},
        messages: {
                        oldpassword:	{ 
				required: "Please enter Old Password"
			},  
			'confnewpass' : {
                                required: "Please confirm your new password",
				equalTo:  "New Password and confirm new password should be same."	
                       },
			newpassword:	{ 
				required: "Please enter New password",
				minlength: 'Please enter at least 6 characters',
				maxlength: 'Password is no more than 50 characters'					
			}
			          
        },
		submitHandler: function(form) {
			$("#login .alert-danger").hide();
                            var formData = $("#userchangepass").serialize();                                    
                            $.post('<?php echo $this->action;?>', formData, function(response){
                                var obj = jQuery.parseJSON( response );
                                var status = obj.status;
                                var msg = obj.msg;                                  
                                if(status == 1){
                                    $("#changepass .alert-error").hide();
                                    $("#changepass .alert-success").show();
                                    $("#changepass .alert-success").html(msg);
								}else if(status == -1){
                                    window.location = '<?php echo $this->url('home') ?>';
                                }else{									
                                    $("#changepass .alert-error").html(msg);
                                    $("#changepass .alert-error").show();
                                    $("#changepass .alert-success").hide();                                    
                                }
								document.getElementById("userchangepass").reset();        
                            });
		}
	});
});      
        
        </script>