<h2 class="heading42"><span><?php echo $username; ?></span></h2>
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="<?php echo $this->url('my-event') ?>">My Events</a></li>
    <li role="presentation"><a href="<?php echo $this->url('order-history') ?>" >Order History</a></li>
    <!--<li role="presentation"><a href="<?php echo $this->url('payment-details') ?>">Payment Details</a></li>-->
    <li role="presentation" class="active"><a href="<?php echo $this->url('userprofile') ?>" role="tab">Settings</a></li>
</ul>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="settings">
        <div class="row">
          <div class="col-md-6">
            <div class="method" id="userinfo">              
              <div class="alert alert-success fade in" style="display:none"></div>
                <div class="alert alert-danger fade in" style="display:none"></div>
                <?php                 
                echo $this->partial('userbasicinfo.phtml', array('form' => $this->basicinfo,'action' => $this->url('basicinfo')));?>       
            </div>
            <!--/basic information-->
            
            <div class="method" id="changepass">
                <div class="alert alert-success fade in" style="display:none"></div>
                <div class="alert alert-danger fade in" style="display:none"></div>
                <?php                 
                echo $this->partial('userchangepassword.phtml', array('form' => $this->changepassword,'action' => $this->url('changepassword')));?>       
            </div>
            <!--/change password-->
            
            <div class="method" id="location">
                <div class="alert alert-success fade in" style="display:none"></div>
                <div class="alert alert-danger fade in" style="display:none"></div>
                <?php                 
                echo $this->partial('userlocation.phtml', array('form' => $this->locationinfo,'action' => $this->url('userlocationinfo')));?>       
              
            </div>
            <!--/location--> 
            
          </div>
        </div>
        <!--/row--> 
    </div>
</div>