<div class="row">
    <div class="col-md-12 pad12">
        <div class="panel panel-default panel-block">
            <div class="list-group">
                <div class="list-group-item" id="masked-input-fields">
                    <h4 class="section-title"> Admin Basic Details </h4>
                    <?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
                    <?php if(!empty($success)) { ?>
                    <div class="alert alert-success"><?php echo $success; ?></div>
                    <?php } ?>
                    <?php if(!empty($error)) { ?>
                    <div class="alert alert-danger fade in"><?php echo $error; ?></div>
                    <?php } ?>
                    <?php
                        $form->setAttribute('action', $this->url('adminsettings'));
                        $form->setAttribute('class', "form-horizontal");
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
                        <label class="col-lg-4 control-label" >
                           From Email
                        </label>
                        <div class="col-lg-8">
                            <?php echo $this->formRow($form->get('email')); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-4 control-label" >
                           Support Email
                        </label>
                        <div class="col-lg-8">
                            <?php echo $this->formRow($form->get('supportemail')); ?>
                        </div>
                    </div>
                    
                    <div class="btnaddriv">
                        <div class="row show-grid">
                            <div class="col-xs-6"><?php echo $this->formRow($form->get('savebtn')); ?></div>
                            <div class="col-xs-6"><button class="btn btn-default saveaddriv unpaistridt" type="button" onclick="window.location ='<?php echo $this->url('admindashboard') ?>';">Cancel</button></div>
                        </div> 
                        
                    </div>

                    <?php echo $this->form()->closeTag(); ?>

                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/jquery.validate.js'); ?>
<script>
$( document ).ready(function() {
	
$("#adminsettings").validate({
        errorClass:'validation-error',
        rules: {				
                email:{ required: true,email:true },
                supportemail: {required: true,email:true }
        },
        messages: {           
                'email' : {
                    required: "Please enter email",
                    email:  "Please enter valid email address."	
                },
                'supportemail' : {
                    required: "Please enter support email",
                    email:  "Please enter valid email address."	
                }
        },
        submitHandler: function(form) {
                form.submit();
        }
    });
});
</script>