<body class="login-page">
        <script>
	        var theme = $.cookie('protonTheme') || 'default';
	        $('body').removeClass (function (index, css) {
	            return (css.match (/\btheme-\S+/g) || []).join(' ');
	        });
	        if (theme !== 'default') $('body').addClass(theme);
        </script>
        <!--[if lt IE 8]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="//browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

       	<?php
            $form->setAttribute('action', $this->basePath().'/admin/login');
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
            <section class="wrapper scrollable animated fadeInDown">
                <section class="panel panel-default">
                    <div class="panel-heading">
                        <div>
                            <img src="<?php echo $this->basePath();?>/img/logo.png" alt="proton-logo">
                            <h1>
                                <span class="title">
                                    Tapetickets
                                </span>                                
                            </h1>
                        </div>
                    </div>
                    <ul class="list-group">                       
                       <?php echo $this->flashMessenger()->render('success', array('alert alert-success'));
                       if(!empty($error)) { ?>
					<div class="alert alert-danger fade in"><?php echo $this->error; ?></div>
                                        
                        <?php } 
                        
                        ?> 
                        <li class="list-group-item">
                            <span class="login-text">
                                Login with your Tapeticket account
                            </span>
                            <div class="form-group">
                                <label for="email">Email Address</label>
                               
								<?php echo $this->formRow($form->get('email')); ?>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                               
								<?php echo $this->formRow($form->get('password')); ?>
                            </div>
                        </li>
                    </ul>
                    <div class="panel-footer">
                      
					   <?php echo $this->formRow($form->get('signin')); ?><br />
                                           <a href="<?php echo $this->basePath().'/admin/forgotpassword' ?>" class="forgot">Forgot Your Password?</a>
                        <br>
                      
                    </div>
                </section>
            </section>
			<?php echo $this->form()->closeTag(); ?>
			<?php 
                            $this->headScript()->prependFile($this->basePath() . '/js/jquery.validate.js');
                            $this->headScript()->appendFile($this->basePath() . '/assets/admin/scripts/login.js'); 
                        ?>
    </body>