<script src="<?php echo $this->basePath('/js/jquery.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/frontend/js/bootstrap3-typeahead.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/event/jquery-ui.js'); ?>"></script>
<script src="<?php echo $this->basePath('/js/jquery.validate.js'); ?>"></script>
<script src="<?php echo $this->basePath('/assets/jquery-countdownTimer/jquery.countdownTimer.js'); ?>"></script> 

<script type="text/javascript">jQuery.noConflict();</script>
<script src="<?php echo $this->basePath('/assets/frontend/js/bootstrap.min.js'); ?>"></script>

<script type="text/javascript">
    $(window).load(function(){
        $('#myModal').modal('show');
    });
</script>
<?php echo $this->headLink()->prependStylesheet($this->basePath('/assets/frontend/css/custom-style.css'))->prependStylesheet($this->basePath('/assets/frontend/css/theme-style.css'))->prependStylesheet($this->basePath('/assets/frontend/css/font-awesome.min.css'))->prependStylesheet($this->basePath('/assets/frontend/css/bootstrap.min.css'))->prependStylesheet($this->basePath('/assets/frontend/css/bootstrap-theme.min.css')); ?>

<div class="container">
  
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Select Cities Events</h4>
        </div>
        <div class="modal-body">
              <div class="row">
                <?php
                foreach ($cities as $key => $value) {
                  ?>
                   <article class="col-sm-6 col-md-4">
                    <a href="#">
                          <div class="boxTile">
                            <div class="square">
                                  <a href="<?php echo $this->basePath().'/events/city/'.$value->getId();?>"><img src="<?php echo $this->basePath().'/img/city_icons/'.$value->getCityImage();?>" /></a>
                            </div>
                            <div class="square info easeAni">
                              <div class="text">
                                <p><?php echo $value->getCityName();?></p>
                              </div>
                            </div>
                          </div>
                    </a>
                    </article>
                  <?php
                }
               ?>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>
<script type='text/javascript'>

    $(document).ready(function() {
$('#myCarousel').carousel({
interval: 10000
})

$('#myCarousel').on('slid.bs.carousel', function() {
alert("slid");
});


});
</script>