<div class="row">
	<div class="col-md-12 pad12">		
		<div class="panel panel-default panel-block">
			<div class="list-group">
				<div class="list-group-item" id="masked-input-fields">
					<h4 class="section-title">Change Password</h4>
					<?php echo $this->flashMessenger()->render('success', array('alert alert-success')); ?>
					<?php if(!empty($error)) { ?>
					<div class="alert alert-danger fade in"><?php echo $this->error; ?></div>
				<?php } ?>
					<?php
						$form->setAttribute('action', $this->url('changepassword'));
						$form->setAttribute('class', "form-horizontal");
						$form->prepare();
						echo $this->form()->openTag($form);
					?>
						<div class="form-group">
							<label class="col-lg-4 control-label" for="firstname">
							   Old Password
							</label>
							<div class="col-lg-8">
								
								<?php echo $this->formRow($form->get('oldpassword')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-lg-4 control-label" for="firstname">
							   New Password
							</label>
							<div class="col-lg-8">
								<?php echo $this->formRow($form->get('newpassword')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-lg-4 control-label" for="firstname">
							   Confirm New Password
							</label>
							<div class="col-lg-8">
								<?php echo $this->formRow($form->get('confnewpass')); ?>
							</div>
						</div>
						<div class="btnaddriv">
                                                    <div class="col-xs-6"><?php echo $this->formRow($form->get('savebtn')); ?></div>
                                                    <div class="col-xs-6"><button class="btn btn-default saveaddriv unpaistridt" type="button" onclick="window.location ='<?php echo $this->url('home') ?>';">Cancel</button></div>						
						</div>
					
					<?php echo $this->form()->closeTag(); ?>
					
				</div>
			</div>
		</div>
	</div>
</div>
<?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/jquery.validate.js'); ?>
<script>
$( document ).ready(function() {
	
	$("#userchangepass").validate({
		errorClass:'validation-error',
		rules: {				
			oldpassword:{ required: true },
			newpassword:{ required: true, minlength: 6, maxlength: 16 },
			confnewpass: { required: true, equalTo: "#newpassword", minlength: 6, maxlength: 16 },
		},
        messages: {           
			'confnewpass' : {
                                required: "Confirm your new password",
				equalTo:  "New Password and confirm new password should be same."	
            },
			newpassword:	{ 
				required: "Enter New password",
				minlength: 'Enter at least 6 characters',
				maxlength: 'Password is no more than 50 characters'					
			},
			oldpassword:	{ 
				required: "Enter Old Password"
			}            
        },
		submitHandler: function(form) {
			form.submit();
		}
	});
});
</script>